-- Bootcamp SQL - Requêtes DQL avec exemples

USE commercial;

-- 1. Clients ayant commandé à la fois Bonbons et Biscuits + coût total
SELECT 
    C.COMPANY AS Client,
    SUM(OD.QUANTITY * OD.UNIT_PRICE) AS Cout_Total
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_ID
JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE CAT.CATEGORY_NAME IN ('Bonbons', 'Biscuits')
GROUP BY C.COMPANY
HAVING COUNT(DISTINCT CAT.CATEGORY_NAME) = 2;

-- 2. Clients ayant commandé des Bonbons + coût total
SELECT 
    C.COMPANY AS Client,
    SUM(OD.QUANTITY * OD.UNIT_PRICE) AS Cout_Bonbons
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_ID
JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE CAT.CATEGORY_NAME = 'Bonbons'
GROUP BY C.COMPANY;

-- 3. Clients ayant commandé des Glaces + coût total
SELECT 
    C.COMPANY AS Client,
    SUM(OD.QUANTITY * OD.UNIT_PRICE) AS Cout_Glaces
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_ID
JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE CAT.CATEGORY_NAME = 'Glaces'
GROUP BY C.COMPANY;

-- 4. Nombre total de Biscuits et Bonbons + coût total
SELECT 
    C.COMPANY AS Client,
    SUM(OD.QUANTITY) AS Quantite_Totale,
    SUM(OD.QUANTITY * OD.UNIT_PRICE) AS Cout_Total
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_ID
JOIN CATEGORIES CAT ON P.CATEGORY_CODE = CAT.CATEGORY_CODE
WHERE CAT.CATEGORY_NAME IN ('Bonbons', 'Biscuits')
GROUP BY C.COMPANY;

-- 5. Clients ayant passé le plus grand nombre de commandes
SELECT 
    C.COMPANY AS Client,
    COUNT(O.ORDER_NUMBER) AS Nb_Commandes
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
GROUP BY C.COMPANY
ORDER BY Nb_Commandes DESC;

-- 6. Produits les plus commandés + quantité totale
SELECT 
    P.PRODUCT_NAME,
    SUM(OD.QUANTITY) AS Quantite_Totale
FROM PRODUCTS P
JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_REF
GROUP BY P.PRODUCT_NAME
ORDER BY Quantite_Totale DESC;

-- 7. Clients ayant passé une commande chaque jour de la semaine
SELECT 
    C.COMPANY AS Client,
    COUNT(DISTINCT DAYNAME(O.ORDER_DATE)) AS Jours_Commandes,
    COUNT(O.ORDER_NUMBER) AS Nb_Commandes
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
GROUP BY C.COMPANY
HAVING Jours_Commandes = 7;
